### ISSUE TITLE
company-keywords backend is not working after recent update

### ISSUE THREAD

**Issue by CsBigDataHub** [jcs-elpa/company-fuzzy#14]
`company-keywords`  backend is not working after the update.

 `company-keywords` doesn't show up at all.

current package-version - `company-fuzzy-20201020-1552`

emacs-version - 27.1

company-version - `0.9.13` - package-version = `company-20201004.735`

**Update** :

Can confirm that it is working until this commit - 2f70e6fe78c45d0cbbb22b1d994f90aa9c78553b
I have tested it using quelpa.
```
(use-package company-fuzzy
  :quelpa
  (company-fuzzy
   :fetcher github
   :repo "jcs-elpa/company-fuzzy"
   :commit "2f70e6fe78c45d0cbbb22b1d994f90aa9c78553b"
   )
  :init
  (setq company-fuzzy-sorting-backend 'flx)
  (setq company-fuzzy-prefix-ontop nil)
  (with-eval-after-load 'company
    (global-company-fuzzy-mode t)))
```

I just tested it with `jenkinsfile-mode`
https://github.com/john2x/jenkinsfile-mode/blob/65bf3925852c35c6bd499978f08f83c1193f4347/jenkinsfile-mode.el#L299

**Comment by jcs090218** [comment]
I have tested with `jenkinsfile-mode` and it works in the latest version. 😕 

I realized that you add keywords to `company-keywords-alist` weather `company` is found. Did company activate in the before `jenkinsfile-mode` is loaded? (Just want to make sure) Otherwise, I am not able to reproduce this issue. 😕 Thanks!

**Comment by CsBigDataHub** [comment]
@jcs090218 Thanks for replying.
Yes company is activated globally at init. I have posted my config here https://github.com/jcs-elpa/company-fuzzy/issues/12#issuecomment-730125989.

I have `company-backends` configured like this -

```
 company-backends '((company-capf :with company-yasnippet)
                           (company-dabbrev-code company-keywords company-files)
                           company-dabbrev))
```
Do you this order of backends will help?

```
(setq company-backends
        (append
         ;; --- Internal ---
         '(company-capf company-semantic)
         '(company-keywords)    ; Put infront of `company-dabbrev'
         '(company-abbrev company-dabbrev company-dabbrev-code)
         '(company-files)
         '(company-etags company-gtags)
         '(company-yasnippet)
         ;; --- External ---
         '(company-emoji)))
```

**Comment by jcs090218** [comment]
> Do you think this order of backends will help?

Yes, In my case `dabbrev` take over some of the `keywords` backend because both of them have the same candidates. This is related to #6. 

Yet `jenkinsfile-mode`'s has a very unique keywords like `ViolationsToGitHub`. I assumed it has no way to be in `dabbrev` backend, then in this case it wouldn't matter. The order is only matters to the annotation. If the candidates like `ViolationsToGitHub` isn't appearing then it is a bug! 😖 But I am not able to reproduce for now!

![ezgif-1-cb137ae64183](https://user-images.githubusercontent.com/8685505/99752853-2125b800-2b20-11eb-995f-f6f07b399e67.gif)

**Comment by CsBigDataHub** [comment]
Let me try that out. Will keep you posted.

**Comment by CsBigDataHub** [comment]
@jcs090218 Thanks for your help. Changing the order did help.
